[package]
name = "serde_vrm"
description = "Serde types for VRM."
keywords = ["serde", "vrm"]
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
bevy = { version = "0.13.2", optional = true }
